% This scripts performs RSA. 

clear 

%%

par_rsa = [];

experiment = '2ioi'; 

par = get_par('experiment', experiment); 

subjects = [num2cell(par.subjects), {'grand'}]; 

feat_name_stim = 'ratio'; % ratio, urear-an

harm_selections = {
    [1:6]
    [1:12]
}; 

flip_rdm = false;

rerun_stats = true; 

rerun_figs = false; 

par_rsa.concat_ep = false; 
par_rsa.feat_snr = false; 

%%

for i_sub=1:length(subjects)

    sub = subjects{i_sub}; 

    % --------------- tapping envelope ERPs ---------------

    par_rsa.lpf_cutoff = par.filt_tap_erp_cut_low; 

    rsa_tap_erp(sub, par_rsa, ...
                   'rerun_stats', rerun_stats, ...
                   'rerun_figs', rerun_figs, ...
                   'feat_stim', feat_name_stim, ...
                   'flip_rdm', flip_rdm, ...
                   'par', par);     

    % --------------- tapping onset ratios ---------------

    rsa_tap_ratios(sub, ...
                   'rerun_stats', rerun_stats, ...
                   'rerun_figs', rerun_figs, ...
                   'flip_rdm', flip_rdm, ...
                   'par', par);     

     % --------------- EEG ERPs ---------------

    par_rsa.lpf_cutoff = par.filt_erp_cut_low; 

    % --> frontal ROI
    par_rsa.avg_chans = true; 
    par_rsa.roi_name = 'front';         

    rsa_erp(sub, par_rsa, ...
           'rerun_stats', rerun_stats, ...
           'rerun_figs', rerun_figs, ...
           'feat_stim', feat_name_stim, ...
           'flip_rdm', flip_rdm, ...
           'par', par); 

    % --> all channels ROI
    par_rsa.avg_chans = false; 
    par_rsa.roi_name = 'all';

    rsa_erp(sub, par_rsa, ...
           'rerun_stats', rerun_stats, ...
           'rerun_figs', rerun_figs, ...
           'feat_stim', feat_name_stim, ...
           'flip_rdm', flip_rdm, ...
           'par', par);    

end

%%

for i_harm_sel=1:length(harm_selections)

    par_rsa.harmonics = harm_selections{i_harm_sel}; 

        %% cochlear model 

        % --------------- UREAR AN ---------------

        rsa_coch(par_rsa, ...
                   'response', 'urear-an', ...
                   'rerun_stats', rerun_stats, ...
                   'rerun_figs', rerun_figs, ...
                   'flip_rdm', flip_rdm, ...
                   'feat_resp', 'X', ...
                   'feat_stim', feat_name_stim, ...
                   'par', par);                 

    for i_sub=1:length(subjects)

        sub = subjects{i_sub}; 

        %% tapping

        % --------------- tapping force ---------------

        % based on complex FFT
        rsa_tap_cont(sub, par_rsa, ...
                   'response', 'tap-force', ...
                   'rerun_stats', rerun_stats, ...
                   'rerun_figs', rerun_figs, ...
                   'flip_rdm', flip_rdm, ...
                   'feat_resp', 'X', ...
                   'feat_stim', feat_name_stim, ...
                   'par', par);     
               
        % based on magnitude FFT
        rsa_tap_cont(sub, par_rsa, ...
                   'response', 'tap-force', ...
                   'rerun_stats', rerun_stats, ...
                   'rerun_figs', rerun_figs, ...
                   'flip_rdm', flip_rdm, ...
                   'feat_resp', 'mX', ...
                   'feat_stim', feat_name_stim, ...
                   'par', par);    
               
        % --------------- tapping impulse ---------------

        % based on complex FFT
        rsa_tap_cont(sub, par_rsa, ...
                   'response', 'tap-impulse', ...
                   'rerun_stats', rerun_stats, ...
                   'rerun_figs', rerun_figs, ...
                   'flip_rdm', flip_rdm, ...
                   'feat_resp', 'X', ...
                   'feat_stim', feat_name_stim, ...
                   'par', par);     
               
        % based on magnitude FFT
        rsa_tap_cont(sub, par_rsa, ...
                   'response', 'tap-impulse', ...
                   'rerun_stats', rerun_stats, ...
                   'rerun_figs', rerun_figs, ...
                   'flip_rdm', flip_rdm, ...
                   'feat_resp', 'mX', ...
                   'feat_stim', feat_name_stim, ...
                   'par', par);     
               
        %% EEG FFT 

        % --> all channels ROI
        par_rsa.avg_chans = false; 
        par_rsa.roi_name = 'all';

        % based on complex FFT
        rsa_eeg_cont(sub, par_rsa, ...
               'rerun_stats', rerun_stats, ...
               'rerun_figs', rerun_figs, ...
               'flip_rdm', flip_rdm, ...
               'feat_resp', 'X', ...
               'feat_stim', feat_name_stim, ...
               'par', par); 

        % based on magnitude FFT
        rsa_eeg_cont(sub, par_rsa, ...
               'rerun_stats', rerun_stats, ...
               'rerun_figs', rerun_figs, ...
               'flip_rdm', flip_rdm, ...
               'feat_resp', 'mX', ...
               'feat_stim', feat_name_stim, ...
               'par', par);            
           
        % --> frontal ROI
        par_rsa.avg_chans = true; 
        par_rsa.roi_name = 'front';         

        % based on complex FFT
        rsa_eeg_cont(sub, par_rsa, ...
               'rerun_stats', rerun_stats, ...
               'rerun_figs', rerun_figs, ...
               'flip_rdm', flip_rdm, ...
               'feat_resp', 'X', ...
               'feat_stim', feat_name_stim, ...
               'par', par); 

        % based on magnitude FFT
        rsa_eeg_cont(sub, par_rsa, ...
               'rerun_stats', rerun_stats, ...
               'rerun_figs', rerun_figs, ...
               'flip_rdm', flip_rdm, ...
               'feat_resp', 'X', ...
               'feat_stim', feat_name_stim, ...
               'par', par); 


    end

end

